import pandas as pd
import numpy as np

COLS_COMPLEMENTO = [
    'DOCUMENTO',
    'PORCENTAJE_CRED_PERDIDOS',
    'ORD_CONV',
    'CREDITOS_PERIODO',
    'PERIODOS_BD_SNIES',
    'JORNADA',
    'TIPO_IES',
    'CREDITOS_PROGRAMA'
]


ETNIAS = [
    'INDIGENA',
    'NEGRO(A), MULATO(A), AFRODESCENDIENTE, AFROCOLOMBIANO(A)',
    'COMUNIDADES NEGRAS O AFROCOLOMBIANAS RAIZALES O PALENQUERAS',
    'RAIZAL DEL ARCHIPIELAGO DE SAN ANDRES, PROVIDENCIA Y SANTA CATALINA',
    'GITANO(A) O RROM',
    'PALENQUERO(A) DE SAN BASILIO'
]

distr_universitario = {
    1:[1],
    2:[0.61, 1],
    3:[0.55, 0.89, 1],
    4:[0.47, 0.77, 0.86, 1],
    5:[0.42, 0.69, 0.77, 0.888, 1],
    6:[0.41, 0.67, 0.75, 0.87, 0.98, 1],
    7:[0.41, 0.67, 0.75, 0.87, 0.98, 0.998, 1],
    8:[0.41, 0.67, 0.75, 0.87, 0.98, 0.998, 1, 1]
}

COLS_TODAS_COMPLEMENTO = ['TIPO_DOCUMENTO', 'DOCUMENTO', 'NIVEL_SISBEN_4', 'SEXO', 'GRUPO_ETNICO',
       'HIJOS', 'EDAD_DEL_CALCULO', 'RANGO_EDAD', 'SNIES_IES', 'TIPO_IES',
       'SNIES_PROGRAMA', 'PROGRAMA', 'NIVEL_FORMACION', 'CINE_CAMPO_AMPLIO',
       'MODALIDAD', 'PERIODICIDAD', 'JORNADA', 'PERIODOS_BD_SNIES',
       'HOMOLOGACION', 'CREDITOS_PERIODO', 'CREDITOS_PROGRAMA',
       'CREDITOS_HOMOLOGADOS', 'ACU_CRED_CONSUMIDOS', 'ACU_CRED_APROBADOS',
       'ACU_CRED_PERDIDOS', 'PORCENTAJE_CRED_CONSUMIDOS',
       'PORCENTAJE_CRED_APROBADOS', 'PORCENTAJE_CRED_PERDIDOS',
       'ALERTA_CRED_PERDIDOS', 'ALERTA_CRED_PERDIDOS_FORMACION',
       'PORCENTAJE_PERIODOS_FINANCIADOS', 'CUPO', 'CAUSAL_ESTADO',
       'CUENTA_APLAZADOS', 'CUENTA_APLAZADOS_TOTAL', 'DUPLICADO', 'ORD_CONV',
       'CONVOCATORIA', 'CONVOCATORIA_LIQ', 'PERIODO_APROBADOS',
       'PERIODO_CONSUMIDOS', 'PERIODO_PERDIDOS', 'PERIODO_ULTIMO_ESTADO',
       'EDAD_RANGO']